// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Point_of_Sale_System.Server.Models.Data;

#nullable disable

namespace Point_of_Sale_System.Server.Migrations
{
    [DbContext(typeof(PoSDbContext))]
    [Migration("20251216060148_ReceiptFix")]
    partial class ReceiptFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeOrganization", b =>
                {
                    b.Property<Guid>("EmployeesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeesId", "OrganizationsId");

                    b.HasIndex("OrganizationsId");

                    b.ToTable("EmployeeOrganization");
                });

            modelBuilder.Entity("MenuServiceTax", b =>
                {
                    b.Property<Guid>("MenuServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaxesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuServicesId", "TaxesId");

                    b.HasIndex("TaxesId");

                    b.ToTable("MenuServiceTax");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.Business.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFlag")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.Business.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.Business.SuperAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuperAdmins");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TaxId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.Variation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("Variations");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApplicableTo")
                        .HasColumnType("int");

                    b.Property<int>("NumberType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.DiscountReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AffectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Procentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("DiscountReceipts");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Giftcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Giftcards");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentOrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VariationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ParentOrderItemId");

                    b.HasIndex("VariationId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<Guid?>("GiftcardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("RefundStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("StripePaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tip")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("GiftcardId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberType")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.TaxReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AffectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberType")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("TaxReceipts");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MenuServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MenuServiceId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.AppointmentReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("AppointmentReceipts");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.MenuService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MenuServices");
                });

            modelBuilder.Entity("EmployeeOrganization", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuServiceTax", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.ServiceBased.MenuService", null)
                        .WithMany()
                        .HasForeignKey("MenuServicesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Tax", null)
                        .WithMany()
                        .HasForeignKey("TaxesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.InventoryItem", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany("InventoryItems")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.MenuItem", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Discount", "Discount")
                        .WithMany("MenuItems")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany("MenuItems")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Tax", "Tax")
                        .WithMany("MenuItems")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Organization");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.Variation", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.MenuBased.MenuItem", "MenuItem")
                        .WithMany("Variations")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.DiscountReceipt", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.ServiceBased.AppointmentReceipt", "Receipt")
                        .WithMany("Discounts")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Giftcard", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Order", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany("Orders")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.OrderItem", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.MenuBased.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.OrderItem", "ParentOrderItem")
                        .WithMany("ChildOrderItems")
                        .HasForeignKey("ParentOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.MenuBased.Variation", "Variation")
                        .WithMany("OrderItems")
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuItem");

                    b.Navigation("Order");

                    b.Navigation("ParentOrderItem");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Payment", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.ServiceBased.Appointment", "Appointment")
                        .WithMany("Payments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Giftcard", "Giftcard")
                        .WithMany("Payments")
                        .HasForeignKey("GiftcardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany("Payments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Giftcard");

                    b.Navigation("Order");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Tax", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.TaxReceipt", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.ServiceBased.AppointmentReceipt", "Receipt")
                        .WithMany("Taxes")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.Appointment", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.ServiceBased.MenuService", "MenuService")
                        .WithMany("Appointments")
                        .HasForeignKey("MenuServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany("Appointments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("MenuService");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.AppointmentReceipt", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.MenuService", b =>
                {
                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Discount", "Discount")
                        .WithMany("MenuServices")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Point_of_Sale_System.Server.Models.Entities.Business.Organization", "Organization")
                        .WithMany("MenuServices")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.Business.Employee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.Business.Organization", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("InventoryItems");

                    b.Navigation("MenuItems");

                    b.Navigation("MenuServices");

                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.MenuItem", b =>
                {
                    b.Navigation("Variations");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.MenuBased.Variation", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Discount", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("MenuServices");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Giftcard", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.OrderItem", b =>
                {
                    b.Navigation("ChildOrderItems");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.OrdersAndPayments.Tax", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.Appointment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.AppointmentReceipt", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("Point_of_Sale_System.Server.Models.Entities.ServiceBased.MenuService", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
